root: true

env:
  browser: true
  node: true
  es2020: true

globals:
  NodeJS: true

extends:
  - '@cordisjs/eslint-config'

rules:
  '@typescript-eslint/naming-convention': off
  '@typescript-eslint/no-unused-vars':
    - error
    - args: none
      ignoreRestSiblings: true
